language: node_js

node_js: 
  - node

install:
  - npm ci

script:
  - npm run lint

branches:
  only:
    - ci

before_deploy:
  - npm run webpack
  - echo -e "node_modules" > .gitignore

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  target-branch: ci
  on:
    branch: ci

notification:
  email:
    - rikovdmitri39@gmail.com