language: node_js

node_js: 
  - node

install:
  - npm ci

script:
  - npm run lint
  - npm run webpack

branches:
  only:
    - ci

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  on:
    branch: ci

notification:
  email:
    - rikovdmitri39@gmail.com